"""Public typed exceptions and the closed redacted factory."""

from librus_python_api.errors import (
    AccessDeniedError,
    AccountActionRequiredError,
    ClosedError,
    ConnectionError,
    CredentialsRejectedError,
    ErrorKind,
    InvalidInputError,
    LibrusError,
    LimitError,
    MaintenanceError,
    OperationTimeoutError,
    ParseError,
    SessionExpiredError,
    ThrottledError,
    UnknownDeliveryError,
    UnsupportedCapabilityError,
    error_for,
)

__all__ = [
    "AccessDeniedError",
    "AccountActionRequiredError",
    "ClosedError",
    "ConnectionError",
    "CredentialsRejectedError",
    "ErrorKind",
    "InvalidInputError",
    "LibrusError",
    "LimitError",
    "MaintenanceError",
    "OperationTimeoutError",
    "ParseError",
    "SessionExpiredError",
    "ThrottledError",
    "UnknownDeliveryError",
    "UnsupportedCapabilityError",
    "error_for",
]
